// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package data_acess

import (
	"database/sql"
)

type Entry struct {
	ID          int64
	Source      string
	Target      string
	Amount      interface{}
	Description sql.NullString
}
