// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package data_acess

import (
	"context"
	"database/sql"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
	source,
	target,
	amount,
	description
) VALUES (?, ?, ?, ?) RETURNING id, source, target, amount, description
`

type CreateEntryParams struct {
	Source      string
	Target      string
	Amount      interface{}
	Description sql.NullString
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry,
		arg.Source,
		arg.Target,
		arg.Amount,
		arg.Description,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Target,
		&i.Amount,
		&i.Description,
	)
	return i, err
}

const deleteEntry = `-- name: DeleteEntry :one
DELETE FROM entries
WHERE id = (?)
RETURNING id, source, target, amount, description
`

func (q *Queries) DeleteEntry(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, deleteEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Target,
		&i.Amount,
		&i.Description,
	)
	return i, err
}

const getAllEntries = `-- name: GetAllEntries :many
SELECT id, source, target, amount, description FROM entries
`

func (q *Queries) GetAllEntries(ctx context.Context) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, getAllEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Target,
			&i.Amount,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntry = `-- name: GetEntry :one
SELECT id, source, target, amount, description FROM entries WHERE id = (?)
`

func (q *Queries) GetEntry(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Target,
		&i.Amount,
		&i.Description,
	)
	return i, err
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE entries
SET source = ?,
target = ?,
amount = ?,
description = ?
WHERE id = (?)
RETURNING id, source, target, amount, description
`

type UpdateEntryParams struct {
	Source      string
	Target      string
	Amount      interface{}
	Description sql.NullString
	ID          int64
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, updateEntry,
		arg.Source,
		arg.Target,
		arg.Amount,
		arg.Description,
		arg.ID,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Target,
		&i.Amount,
		&i.Description,
	)
	return i, err
}
